
/* los bucles while (mientras) y do-while (hacer-mientras) son muy parecidos. Ambos verifican que se cumpla una condición en particular. 
El diferenciador es cuándo verifican que se cumple la condición. 
Los bucles while comprueban la condición antes de iniciar el bucle y los bucles do-while la comprueban después de finalizar el bucle.  */

While (condition) {
    //run this block of code
}

Do {
    //run this block of code
} while(condition);